### ISSUE TITLE
Error when cargo fuzz

### ISSUE THREAD

**Issue by surechen** [dtolnay/semver#288]
I'm using cargo-fuzz for fuzz testing, my test case relies on a libxxxxx.so developed by Rust language.

I add build.rs to this libxxxxx.so:
```rust
fn main() {
    println!("cargo:rustc-link-arg=-fsanitize=address");
    println!("cargo:rustc-link-arg=-lasan");
}
```

I do fuzz for my example like this.
```shell
LD_PRELOAD=/lib/x86_64-linux-gnu/libasan.so.5 cargo fuzz run fuzz_target_1
```
error is: 
```shell
Direct leak of 23 byte(s) in 1 object(s) allocated from:
    #0 0x7f49e5b7b808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55b38dad4ce6 in <semver::identifier::Identifier as core::clone::Clone>::clone (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo+0xd25ce6)

Direct leak of 23 byte(s) in 1 object(s) allocated from:
    #0 0x7f49e5b7b808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x55b38dad3a51 in semver::parse::build_identifier (/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo+0xd24a51)


SUMMARY: AddressSanitizer: 46 byte(s) leaked in 2 allocation(s).
Error: failed to build fuzz script: "cargo" "build" "--manifest-path" "/usr/local/src/rust/xxxxxx/examples/xxxxxxxx/fuzz/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "--release" "--bin" "fuzz_target_1"
```
My cargo version is cargo 1.64.0-nightly (d8d30a753 2022-07-19)
I am not sure if this is caused by Semver, because of this error message, I would like to seek some advices, thank you very much.

**Comment by dtolnay** [comment]
I don't think this is related to code in this crate. But you'd get this if some other crate you use is leaking a semver::Version.
